var By = require('selenium-webdriver').By;

var navBarContacts = By.xpath("//div[@id='mainNavBar']//a[@data-hint='Contacts']"),
    navBarMatters = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Matters']"),
    navBarNew = By.xpath("//div[@id='mainNavBar']//a[@data-hint='New']"),
        navBarNewContact = By.xpath("//div[@id='mainNavBar']//a[@data-hint='Contact']"),
            navBarNewContactPerson = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Create Person']"),
            navBarNewContactCompany = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Create Company']"),
        navBarNewEmails = By.xpath("//div[@id='mainNavBar']//a[@data-pe-dialog='/EmailMessages/Create']"),
        navBarNewTask = By.xpath("//div[@id='mainNavBar']//a[text()='Task']"),
        navBarNewAppointment = By.xpath("//div[@id='mainNavBar']//a[text()='Appointment']"),
        navBarNewAcitivity = By.xpath("//div[@id='mainNavBar']//a[text()='Activity']"),
        navBarNewMatter = By.xpath("//div[@id='mainNavBar']//a[text()='Matter']"),
        navBarNewNewClientIntake = By.xpath("//div[@id='mainNavBar']//a[text()='New Client Intake']"),
    navBarView = By.xpath("//div[@id='mainNavBar']//a[@data-hint='View']"),
        navBarViewCalendar = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Calendar']"),
        navBarViewEmails = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Emails']"),
        navBarViewTasks = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Tasks']"),
        navBarViewAcitivities = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Activities']"),
        navBarViewDocuments = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Documents']"),
        navBarViewDocumentTemplates = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Document Templates']"),
        navBarViewDeposit = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Deposit']"),
        navBarViewMaintenance = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Maintenance']"),
        navBarViewExpenses = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Expenses']"),
        navBarViewImport = By.xpath("//div[@id='mainNavBar']//a[@data-pe-tab='Import']");

var navBarOverview = By.xpath("//ul[@id='schedulesView']/li[1]/a"),
    navBarEvents = By.xpath("//ul[@id='schedulesView']/li[2]/a"),
        navBarEventsTasks = By.xpath("//div[starts-with(@id, 'CaseViewEventsContent_')]//a[text()='Tasks']"),
        navBarEventsAppointments = By.xpath("//div[starts-with(@id, 'CaseViewEventsContent_')]//a[text()='Appointments']"),
        navBarEventsActivities = By.xpath("//div[starts-with(@id, 'CaseViewEventsContent_')]//a[text()='Activities']"),
    navBarManage = By.xpath("//ul[@id='schedulesView']/li[3]/a"),
        navBarManageEmailMessages = By.xpath("//div[starts-with(@id, 'CaseViewManageContent_')]//a[text()='Email Messages']"),
        navBarManageDocuments = By.xpath("//div[starts-with(@id, 'CaseViewManageContent_')]//a[text()='Documents']"),
        navBarManageMatterForms = By.xpath("//div[starts-with(@id, 'CaseViewManageContent_')]//a[text()='Matter Forms']"),
        navBarManageFinance = By.xpath("//div[starts-with(@id, 'CaseViewManageContent_')]//a[text()='Finance']"),
        navBarManageAssociatedParties = By.xpath("//div[starts-with(@id, 'CaseViewManageContent_')]//a[starts-with(@href, '#CaseViewParties_')]"),
        navBarManageCaseHistory = By.xpath("//div[starts-with(@id, 'CaseViewManageContent_')]//a[starts-with(@href, '#CaseViewHistory_')]"),
    navBarPetition = By.xpath("//ul[@id='schedulesView']/li[4]/a"),
        navBarPetitionGeneralInformation = By.xpath("//div[starts-with(@id, 'CaseViewPetitionContent_')]//a[starts-with(@href, '#CaseInformation_')]"),
        navBarPetitionProperty = By.xpath("//div[starts-with(@id, 'CaseViewPetitionContent_')]//a[starts-with(@href, '#CaseProperty_')]"),
        navBarPetitionCreditors = By.xpath("//div[starts-with(@id, 'CaseViewPetitionContent_')]//a[starts-with(@href, '#CaseCreditors_')]"),
        navBarPetitionExecutoryContracts = By.xpath("//div[starts-with(@id, 'CaseViewPetitionContent_')]//a[starts-with(@href, '#CaseExecutoryContracts_')]"),
        navBarPetitionIncomeAndExpenses = By.xpath("//div[starts-with(@id, 'CaseViewPetitionContent_')]//a[starts-with(@href, '#CaseIncome_')]"),
        navBarPetitionSofa = By.xpath("//div[starts-with(@id, 'CaseViewPetitionContent_')]//a[starts-with(@href, '#CaseSofa_')]"),
        navBarPetitionStatementOfIntent = By.xpath("//div[starts-with(@id, 'CaseViewPetitionContent_')]//a[starts-with(@href, '#CaseStatementOfIntent_')]"),
        navBarPetitionDueDiligence = By.xpath("//div[starts-with(@id, 'CaseViewPetitionContent_')]//a[starts-with(@href, '#CaseVendors_')]"),
    navBarCourt = By.xpath("//ul[@id='schedulesView']/li[5]/a"),
        navBarCourtCourtview = By.xpath("//div[starts-with(@id, 'CaseViewCourtContent_')]//a[starts-with(@href, '#CaseCourtView_')]"),
        navBarCourtFiling = By.xpath("//div[starts-with(@id, 'CaseViewCourtContent_')]//a[starts-with(@href, '#CaseViewEfiling_')]");
        
var navBarTabHome = By.xpath("//div[@id='AppTabs']/ul[@role='tablist']/li/a[@href='#tab0']");

module.exports = {
    navBarContacts: navBarContacts,
    navBarMatters: navBarMatters,
    navBarNew: navBarNew,
        navBarNewContact: navBarNewContact,
            navBarNewContactPerson: navBarNewContactPerson,
            navBarNewContactCompany: navBarNewContactCompany,
        navBarNewEmails: navBarNewEmails,
        navBarNewTask: navBarNewTask,
        navBarNewAppointment: navBarNewAppointment,
        navBarNewAcitivity: navBarNewAcitivity,
        navBarNewMatter: navBarNewMatter,
        navBarNewNewClientIntake: navBarNewNewClientIntake,
    navBarView: navBarView,
        navBarViewCalendar: navBarViewCalendar,
        navBarViewEmails: navBarViewEmails,
        navBarViewTasks: navBarViewTasks,
        navBarViewAcitivities: navBarViewAcitivities,
        navBarViewDocuments: navBarViewDocuments,
        navBarViewDocumentTemplates: navBarViewDocumentTemplates,
        navBarViewDeposit: navBarViewDeposit,
        navBarViewMaintenance: navBarViewMaintenance,
        navBarViewExpenses: navBarViewExpenses,
        navBarViewImport: navBarViewImport,

    navBarOverview: navBarOverview,
    navBarEvents: navBarEvents,
        navBarEventsTasks: navBarEventsTasks,
        navBarEventsAppointments: navBarEventsAppointments,
        navBarEventsActivities: navBarEventsActivities,
    navBarManage: navBarManage,
        navBarManageEmailMessages: navBarManageEmailMessages,
        navBarManageDocuments: navBarManageDocuments,
        navBarManageMatterForms: navBarManageMatterForms,
        navBarManageFinance: navBarManageFinance,
        navBarManageAssociatedParties: navBarManageAssociatedParties,
        navBarManageCaseHistory: navBarManageCaseHistory,
    navBarPetition: navBarPetition,
        navBarPetitionGeneralInformation: navBarPetitionGeneralInformation,
        navBarPetitionProperty: navBarPetitionProperty,
        navBarPetitionCreditors: navBarPetitionCreditors,
        navBarPetitionExecutoryContracts: navBarPetitionExecutoryContracts,
        navBarPetitionIncomeAndExpenses: navBarPetitionIncomeAndExpenses,
        navBarPetitionSofa: navBarPetitionSofa,
        navBarPetitionStatementOfIntent: navBarPetitionStatementOfIntent,
        navBarPetitionDueDiligence: navBarPetitionDueDiligence,
    navBarCourt: navBarCourt,
        navBarCourtCourtview: navBarCourtCourtview,
        navBarCourtFiling: navBarCourtFiling,

    navBarTabHome: navBarTabHome,
}

